if(navigator.userAgent.match(/Android/i)
|| navigator.userAgent.match(/webOS/i)
|| navigator.userAgent.match(/iPhone|iPad|iPod/i)
|| navigator.userAgent.match(/BlackBerry/i)
|| navigator.userAgent.match(/Windows Phone/i)
|| navigator.userAgent.match(/Opera Mini/i)
|| navigator.userAgent.match(/IEmobile/i)
    ){
        console.log("celular")
    }else{
        console.log("PC")
    }
    /*método do cosole retornar em qual dispositivo está sendo executado o script*/

    